Update ci_pipeline_web.yml

diff --git a/.github/workflows/ci_pipeline_web.yml b/.github/workflows/ci_pipeline_web.yml
--- a/.github/workflows/ci_pipeline_web.yml
+++ b/.github/workflows/ci_pipeline_web.yml
@@ -67,6 +67,11 @@ jobs:
           echo "Intentando conexión SSH con verbosidad:"
           ssh -v -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 ${{ secrets.GCE_USER_FRONT_WEB }}@${{ secrets.GCE_HOST_FRONT_WEB }} "echo Conexión exitosa"
 
+      - name: Clean target directory
+        run: |
+          # Limpiar el directorio de destino antes del despliegue
+          ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_USER_FRONT_WEB }}@${{ secrets.GCE_HOST_FRONT_WEB }} "find /var/www/html/ -mindepth 1 -delete || echo 'Error al eliminar archivos'"
+
       - name: Deploy to production server
         uses: appleboy/scp-action@v0.1.3
         with:
@@ -76,11 +81,10 @@ jobs:
           port: 22
           source: "WebApp/dist/web-app/browser/*"
           target: "/var/www/html/"
-          rm: true
           strip_components: 0
           debug: true
 
       - name: Restart Nginx
         run: |
-          # Reiniciar nginx
+          # Reiniciar Nginx para aplicar cambios
           ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_USER_FRONT_WEB }}@${{ secrets.GCE_HOST_FRONT_WEB }} "sudo systemctl restart nginx && echo 'Despliegue completado con éxito.'"
